name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs: {}

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5
